### ISSUE TITLE
The generation fails

### ISSUE THREAD

**Issue by zhuzhzh** [fcying/compiledb-go#1]
<img width="1266" alt="qMT1phsYtY240823154432" src="https://github.com/user-attachments/assets/5e06c91f-bb87-45a0-909d-44f7f4b714b0">

The tools appends the current directory to the original full path

**Comment by fcying** [comment]
fixed it in the commit `7b7f7a5a136`. You can test it.

**Comment by fcying** [comment]
> > fixed it in the last commit, You can test it.
> 
> I try to use it, and already get same result: " not exist", compiledb seems don't support subdirs?

Is there a log? Let me check where the error occurred. The latest version added the `IsAbsPath` check file path, so the working directory is only added if the path is relative. It seems the addition is incorrect.

**Comment by fcying** [comment]
> ```
> g di
> ```

It seems `working directory` switch is incorrect, as there is no log "change workingDir."
I'll check to see where the issue is.

**Comment by fcying** [comment]
> Thank you. I used the command **compiledb -nv make**

`make_enter_dir` rule has problem,  update regexp for ``` and, `"`,  test and see if it works.

**Comment by fcying** [comment]
> > > Thank you. I used the command **compiledb -nv make**
> > 
> > 
> > `make_enter_dir` rule has problem,  last commit update `make_enter_dir` rule for ` and ",   you can test it.
> 
> Thanks, it works perfect!

great~ thanks for report
