### ISSUE TITLE
Support script

### ISSUE THREAD

**Issue by wangp-blog** [fcying/compiledb-go#2]
Does compiledb currently support compile scripts? Are you interested in making this happen?
Some additional information:
For example, the script I use is called **build.sh**, which includes actions such as determining the system type (x64/arm), executing **Makefile** files and packaging files.
And the execution process of the Makefile file be recognized in this situation and generate a JSON file in the same level path as build.sh?

I try to resolve above problem by other ways, such as use args, and I couldn't understand the meanings of these args:
```cpp
--build-dir Path, -d Path  Path to be used as initial build dir.
--full-path                Write full path to the compiler executable.
```
- I test **-d Path**, and it doesn't work as I expected. I think it means that the path of **Makefile**, but it found wrong path. 
 [*compiledb -nv -d ./src/ make*], current path is **/home/test** and *./src* have a **Makefile** file. There is log file:
```cpp
INFO[0000] compiledb-go start, version: v1.3.2          
INFO[0000] {stdin compile_commands.json ./src/vod/   ^.*-?(gcc|clang|cc|g\+\+|c\+\+|clang\+\+)-?.*(\.exe)? ^.*\s-c.*\s(.*\.(c|cpp|cc|cxx|c\+\+|s|m|mm|cu))(\s.*$|$) false false true false} 
INFO[0000] workingDir: ./src/                       
DEBU[0000] New command:make: Entering directory `/home/test' 
INFO[0000] change workingDir: /home/test 
DEBU[0000] New command:make: *** No targets specified and no makefile found.  Stop. 
DEBU[0000] New command:make: Leaving directory `/home/test'
```

- I test **--full-path**, and it also doesn't work as I expected. 
*compiledb -nv --full-path /home/test//src/ make*
The log file:
```cpp
INFO[0000] compiledb-go start, version: v1.3.2          
INFO[0000] {stdin compile_commands.json    ^.*-?(gcc|clang|cc|g\+\+|c\+\+|clang\+\+)-?.*(\.exe)? ^.*\s-c.*\s(.*\.(c|cpp|cc|cxx|c\+\+|s|m|mm|cu))(\s.*$|$) false true true false} 
INFO[0000] Build from stdin                             

```

**Comment by fcying** [comment]
you can try `./build.sh | compiledb`
it will transfer build.sh output to compiledb

**Comment by fcying** [comment]
--build-dir Path, -d Path:
only init the working directory(will be changed by `Entering directory` command ), if not set, use current directory
--full-path                Write full path to the compiler executable.
use compiler full path(if exist), ex: gcc -> /usr/bin/gcc


> > you can try `./build.sh | compiledb` it will transfer build.sh output to compiledb
> 
> Thank you. This way could correctly compile, but the option _-n_ can't work.
> 
> Could the path of compiledb execution be inconsistent with the **Makefile** path? What happens? Is this action allowed.

`-n` is only work for wrap make, ex: `compile -n make -f ../Makefile`, it not parse input log,  it parse `make -Bnkw` output.

**Comment by fcying** [comment]
> I test it by set option _-d_, but the dir is wrong. And I also test _/home/test/src_, it doesn't work too.

`-d`  is work for parse, error log is not found makefile, you need use `-f` to specify makefile
ex: compiledb -n make -f /home/test/src/Makefile, and then , compiledb will run `make -Bnkw -f /home/test/src/Makefile` and get it's output to parse.

**Comment by fcying** [comment]
> > > I test it by set option _-d_, but the dir is wrong. And I also test _/home/test/src_, it doesn't work too.
> > 
> > 
> > `-d` is work in parse stage, error log is not found makefile(in makewrap stage), you need use `-f` to specify makefile ex: `compiledb -n make -f /home/test/src/Makefile`, and then , compiledb will run `make -Bnkw -f /home/test/src/Makefile` and get it's output to parse.
> 
> Thank you for attention. After I test this `compiledb -n make -f /home/test/src/Makefile`, and I found that there seems to be a new issue when the Makefile contains subdirs. You can check for this and it should be caused by a path concatenation error.

Will running `make -Bnkw -f /home/test/src/Makefile` directly cause an error? compiledb just run this command to get log.

**Comment by fcying** [comment]
> > > > > I test it by set option _-d_, but the dir is wrong. And I also test _/home/test/src_, it doesn't work too.
> > > > 
> > > > 
> > > > `-d` is work in parse stage, error log is not found makefile(in makewrap stage), you need use `-f` to specify makefile ex: `compiledb -n make -f /home/test/src/Makefile`, and then , compiledb will run `make -Bnkw -f /home/test/src/Makefile` and get it's output to parse.
> > > 
> > > 
> > > Thank you for attention. After I test this `compiledb -n make -f /home/test/src/Makefile`, and I found that there seems to be a new issue when the Makefile contains subdirs. You can check for this and it should be caused by a path concatenation error.
> > 
> > 
> > Will running `make -Bnkw -f /home/test/src/Makefile` directly cause an error? compiledb just run this command to get log.
> > Or is it an error in the parse stage? Could you upload the log for analysis?
> 
> Yes, it also cause an error . Maybe the command of `make` prase error.

Some Makefile configurations maybe not support specifying a makefile with -f. 
In this case, change the working directory for makewrap maybe work. 
in last commit, `-d` option will change makewrap working dir.
you can try it with  `compiledb -d /home/test/src  -n make`,

**Comment by fcying** [comment]
> This line `change workingDir: /home/test` maybe cause an error.

bump version now. you can update it, or use version in github action.

**Comment by fcying** [comment]
> > Some Makefile configurations maybe not support specifying a makefile with -f. In this case, change the working directory for makewrap maybe work. in last commit, `-d` option will change makewrap working dir. you can try it with `compiledb -d /home/test/src -n make`.
> 
> Thank you for your patience. Currently, `compiledb - d/home/test/src - n make` can be done normally and output a JSON file.
> 
> But I still have a question, can the `-d NewPath` option be considered as compiledb switching the working path to _NewPath_, which is equivalent to specifying the Makefile file for make, causing the json file to appear in the NewPath.
> 
> **compiledb** is usually placed under`/usr/bin` and appears as a global tool. If compiledb is executed in a certain path, it means that the user expects to generate a JSON file in this path; If after `- d` specifies a new path, json also appears in the new path, why not execute the **compiledb** command directly in the new path.
> 
> * My idea is whether it is possible to specify a new path `-d`, which usually refers to the path where the **Makefile** is located, while the output path of the JSON file is set to the current path of the **compiledb** command by default.

yes, last version `-d` change compiledb working dir, by default output file save to working dir, if you want save to current dir,
you can use `compiledb - d /home/test/src -o $PWD/compile_commands.json -n make`

**Comment by fcying** [comment]
> > yes, last version `-d` change compiledb working dir, by default output file save to working dir, if you want save to current dir, you can use `compiledb -d /home/test/src -o $PWD/compile_commands.json -n make`
> 
> `compiledb` works very well. Currently, we are only discussing this issue: _which directory should the JSON file be output to, and whether it should be in the current dir or the working dir of `compiledb`_. Thanks again.

I just test compiledb-python, it save json in current dir(not effect with -d), I will fix it in next version

**Comment by fcying** [comment]
> > yes, last version `-d` change compiledb working dir, by default output file save to working dir, if you want save to current dir, you can use `compiledb -d /home/test/src -o $PWD/compile_commands.json -n make`
> 
> `compiledb` works very well. Currently, we are only discussing this issue: _which directory should the JSON file be output to, and whether it should be in the current dir or the working dir of `compiledb`_. Thanks again.

done with 1.3.4, you can try a test
